image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - dockerhub

.docker-login: &docker-login
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}

.docker-build: &docker-build
  script:
    - docker build --pull --force-rm=true --squash 
        --build-arg VCS_REF=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` 
        --build-arg PGV=$(grep -o -E "[0-9][0-9]\.[0-9]" VERSION) 
        --tag=${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

docker:latest:
  stage: build
  only: 
    - master
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  <<: *docker-login
  <<: *docker-build

docker:release:
  stage: build
  only:
    - tags
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}
  <<: *docker-login
  <<: *docker-build

dockerhub:
  stage: dockerhub
  script:
    - curl -s -H 'Content-Type:application/json' --data "{\"source_type\":\"Tag\",\"source_name\":\"${CI_COMMIT_REF_NAME}\"}" -X POST https://registry.hub.docker.com/u/datacore/postgresql/trigger/${DOCKERHUB_TOKEN}/ > /dev/null
