stages:
  - build
  - deploy
  - clean
  
build:
  stage: build
  tags: 
    - shell
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH} .
    
release:
  stage: build
  tags: 
    - shell
  only:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION) .

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}

deploy-release:
  stage: deploy
  tags:
    - shell
  only:
    - tags
  script:
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)
    
clean:
  stage: clean
  tags:
    - shell
  script:
    - if [ ! -z $(docker images -q $(cat REPOSITORY)/${CI_PROJECT_PATH}) ]; then docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}; fi

clean-release:
  stage: clean
  tags:
    - shell
  only:
    - tags
  script:
    - if [ ! -z $(docker images -q $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)) ]; then docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION); fi
